### ISSUE TITLE
Fast memory leak on insert Patient

### ISSUE THREAD

**Issue by jonasja79** [furore-fhir/spark#97] opened 2016-08-18 07:47 UTC
Hi,
using the ".NET FhirClient for FHIR 1.0.2". My testserver, and also http://spark.furore.com/. Seems to be taken down by a memory leak. When I try to insert a simple Patient:
"&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;&lt;name&gt;&lt;family value=&quot;jonas delete3&quot; /&gt;&lt;given value=&quot;test&quot; /&gt;&lt;/name&gt;&lt;telecom&gt;&lt;value value=&quot;jonas3@test.no&quot; /&gt;&lt;/telecom&gt;&lt;telecom /&gt;&lt;/Patient&gt;"

**Comment by mbaltus** [comment] 2016-08-22 13:46
Could you please check the xml above, because I cannot reproduce the issue since it is incorrectly formatted now. When I change it to a correct format, both my local and the spark server respond correctly.

**Comment by jonasja79** [comment] 2016-08-23 08:32
Hi, this is a postman query with the same result:
`POST /fhir/Patient HTTP/1.1
Host: 80.241.95.124
User-Agent: .NET FhirClient for FHIR 1.0.2
Accept: application/xml+fhir;charset=utf-8
Prefer: return=representation
Content-Type: application/xml+fhir;charset=utf-8
Cache-Control: no-cache
Postman-Token: c39121c2-17d0-f677-feb3-4ee4ac62bfc2

<Patient xmlns="http://hl7.org/fhir"><name><family value="jonas delete3" /><given value="test" /></name><telecom><value value="jonas3@test.no" /></telecom><telecom /></Patient>`

**Comment by mbaltus** [comment] 2016-08-23 08:47
Thank you!
I can now reproduce the issue. Actually your xml is incorrect, since there's an empty <telecom /> element at the end. If I take that out, the server responds quickly. But the server should either ignore the empty element or give an error, instead of not responding at all, so we'll look into that.

**Comment by jonasja79** [comment] 2016-08-23 08:58
Hi,
Yes, that is correct, I forgot to check if there was a phone number before trying to insert it.
But I figured as you do to, that this should not restart the server :-)
Thank you for following up.

**Comment by CorinaCiocanea** [comment] 2016-08-30 13:00
I have solved the memory leak issue.
But we still have an issue here:
- if the above resource is sent as json, one would receive a 400 response status, since the input is invalid
- if the above resource is sent as xml (as above), one would receive a 500 response status (due to a difference in parsing json and xml strings)

**Comment by CorinaCiocanea** [comment] 2016-09-09 11:09
So, like I said in the previous comment, I solved the memory leak issue. The other issue is dependent on a inconsistency in the FHIR API  and will be fixed by fixing that one. So. I am closing this issue.

**Closed by CorinaCiocanea** 2016-09-09 11:09 UTC
Labels: bug
