### ISSUE TITLE
Conditional Create not working

### ISSUE THREAD

**Issue by Crudelus** [furore-fhir/spark#98] opened 2016-08-24 08:14 UTC
Currently the Conditional Create seems to not work properly. I Create the Example Substance with a POST:

`<Substance xmlns="http://hl7.org/fhir">
 
  <text><status value="generated"/><div xmlns="http://www.w3.org/1999/xhtml"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: example</p><p><b>identifier</b>: 1463</p><p><b>category</b>: Allergen <span>(Details : {http://hl7.org.fhir/substance-category code 'allergen' = '??', given as 'Allergen'})</span></p><p><b>code</b>: apitoxin (Honey Bee Venom) <span>(Details )</span></p></div></text><identifier>
    <system value="http://acme.org/indentifiers/substances"/>
    <value value="1463"/>
  </identifier>
  <category>
    <coding>
      <system value="http://hl7.org.fhir/substance-category"/>
      <code value="allergen"/>
      <display value="Allergen"/>
    </coding>
  </category>
  <code>
    <text value="apitoxin (Honey Bee Venom)"/>
  </code>
</Substance>`

and the additional Header:  If-None-Exist: Substance?identifier=http://acme.org/indentifiers/substances|1463
multiple times, but always got the 201 Created header instead a 200 OK with a content location according to the prior created resource. 

According to FHIR Rest API: [Link](https://www.hl7.org/fhir/http.html#ccreate)

Thank you for your splendid work,
Daniel

**Comment by CorinaCiocanea** [comment] 2016-08-29 13:42
Hello, 

The documentation specifies that **"The parameter just contains the search parameters (what would be in the URL following the "?")."**
So in your case the header should be **If-None-Exist: identifier=http://acme.org/indentifiers/substances|1463**.

So, we actually solved a bug.
Does this help you?

Thank you for your feedback,
Corina

**Comment by Crudelus** [comment] 2016-08-29 15:03
Yes this would help me, but i tried it with the correct format you suggested:

I tried it with your http://spark-dstu2.furore.com/ Server and still only got 201 Created Responses. To check if it might be my fault i also tried the exact same setup with the http://fhirtest.uhn.ca/baseDstu2/ Server from HAPI and there i got the expected results (201 new resource, 200 one existing resource, 412 with more than one match)

Do I have to do anything else to active a Conditional Create on a Server?

**Comment by mharthoorn** [comment] 2016-08-30 07:47
This is not yet updated in the Spark server (spark.furore.com). We will update it soon.

**Comment by CorinaCiocanea** [comment] 2016-09-09 11:05
We will do a redeploy of spark next week and since the issue is solved in the source code I will close this issue. Please let me know if you encounter other issues abut this after the redeploy.

**Closed by CorinaCiocanea** 2016-09-09 11:05 UTC
Labels: duplicate, feature
